# Data Science with Python Assignment 1
### Step 1: Read the CSV File

In [12]:
import pandas as pd

df = pd.read_csv('pandas_dataset.csv')
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

### Step 2: Rename Columns

In [13]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

### Step 3: Drop Unnecessary Rows

In [14]:
initial_shape = df.shape
df = df.dropna(how='all')
df = df.reset_index(drop=True)

### Step 4: Drop Columns

In [15]:
df = df.drop(columns=['order_date'])

### Step 5: Count Missing Values

In [16]:
missing_values = df.isnull().sum()
print("Missing values:\n", missing_values)

Missing values:
 order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
status           1
sales            3
profit           3
discount         3
dtype: int64

### Step 6: Handle Missing Values

In [17]:
df = df.dropna(subset=['sales'])
df['profit'] = df['profit'].fillna(df['profit'].mean())
df['discount'] = df['discount'].fillna(df['discount'].median())

### Step 7: Handle Missing Categorical Data

In [18]:
df['customer_name'] = df['customer_name'].fillna('Unknown')

### Step 8: Detect and Remove Duplicates

In [19]:
duplicates_count = df.duplicated(subset=['order_id']).sum()
print(f"Duplicates found: {duplicates_count}")
df = df.drop_duplicates(subset=['order_id'])

Duplicates found: 3

### Step 9: Filtering and creating new columns

In [20]:
high_price = df[df['unit_price'] > 20000]
display(high_price)

filtered_orders = df[(df['unit_price'] > 10000) & (df['status'] == 'Completed')]
display(filtered_orders[['customer_name', 'category', 'status']])

df['total_amount'] = (df['quantity'] * df['unit_price']) - df['discount']
df['customer_type'] = df['quantity'].apply(lambda x: 'Bulk Buyer' if x >= 3 else 'Regular Buyer')

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.0,5600.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.0,1100.0

   customer_name     category     status
0          Aarav  Electronics  Completed
1           Sita    Furniture  Completed
6          Nabin    Furniture  Completed
12        Roshan  Electronics  Completed
16         Manoj    Furniture  Completed
19          Rita  Electronics  Completed
24        Bikash    Furniture  Completed

### Step 10: Final Clean Dataset

In [21]:
print(f"Shape before cleaning: {initial_shape}")
print(f"Shape after cleaning: {df.shape}")
df.head(10)

Shape before cleaning: (27, 12)
Shape after cleaning: (20, 13)

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount,total_amount,customer_type
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0,153000.0,Regular Buyer
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.0,900.0,17100.0,Regular Buyer
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.0,675.0,12825.0,Bulk Buyer
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.0,650.0,12350.0,Regular Buyer
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0,49500.0,Regular Buyer
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.0,440.0,8360.0,Bulk Buyer
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0,45000.0,Regular Buyer
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.0,1125.0,21375.0,Bulk Buyer
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.0,350.0,6650.0,Regular Buyer
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.0,450.0,8550.0,Bulk Buyer